public class Demo {
	//Decimal a=7,b=2;
    
    public static void addition(){
        Decimal a=7,b=2;
        Decimal add;
        add=a+b;
        System.debug('Addition = '+add);
    }
    
    public static void subtraction(){
        Decimal a=7,b=2;
        Decimal sub;
        sub=a-b;
        System.debug('Subtraction = '+sub);
    }
    
    public static void Multiplication(){
        Decimal a=7,b=2;
        Decimal mul;
        mul=a*b;
        System.debug('Multiplication = '+mul);
    }
    
    public static void Divison(){
        Decimal a=7,b=2;
        Decimal div;
        Div=a/b;
		System.debug('Divison = '+div);
    }
}